/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const CalculatorLazyImport = createFileRoute('/calculator')()
const IndexLazyImport = createFileRoute('/')()
const CurrenciesCodeLazyImport = createFileRoute('/currencies/$code')()

// Create/Update Routes

const CalculatorLazyRoute = CalculatorLazyImport.update({
  path: '/calculator',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calculator.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CurrenciesCodeLazyRoute = CurrenciesCodeLazyImport.update({
  path: '/currencies/$code',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/currencies.$code.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorLazyImport
      parentRoute: typeof rootRoute
    }
    '/currencies/$code': {
      id: '/currencies/$code'
      path: '/currencies/$code'
      fullPath: '/currencies/$code'
      preLoaderRoute: typeof CurrenciesCodeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CalculatorLazyRoute,
  CurrenciesCodeLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calculator",
        "/currencies/$code"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/calculator": {
      "filePath": "calculator.lazy.tsx"
    },
    "/currencies/$code": {
      "filePath": "currencies.$code.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
