/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'

// Create Virtual Routes

const CurrenciesCodeLazyImport = createFileRoute('/currencies/$code')()
const indexIndexLazyImport = createFileRoute('/(index)/')()

// Create/Update Routes

const CurrenciesCodeLazyRoute = CurrenciesCodeLazyImport.update({
  path: '/currencies/$code',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/~currencies/~$code.lazy').then((d) => d.Route),
)

const indexIndexLazyRoute = indexIndexLazyImport
  .update({
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/~(index)/~index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(index)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/currencies/$code': {
      id: '/currencies/$code'
      path: '/currencies/$code'
      fullPath: '/currencies/$code'
      preLoaderRoute: typeof CurrenciesCodeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  indexIndexLazyRoute,
  CurrenciesCodeLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/currencies/$code"
      ]
    },
    "/": {
      "filePath": "~(index)/~index.lazy.tsx"
    },
    "/currencies/$code": {
      "filePath": "~currencies/~$code.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
